# Generated by Django 3.2.23 on 2024-03-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderonline', '0017_auto_20240227_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('county', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('extras', models.ManyToManyField(blank=True, related_name='_checkout_orderlineitem_extras_+', to='orderonline.MenuItemIngredient')),
                ('included_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orderonline.menuitem')),
                ('included_item_extras', models.ManyToManyField(blank=True, related_name='_checkout_orderlineitem_included_item_extras_+', to='orderonline.MenuItemIngredient')),
                ('included_item_options', models.ManyToManyField(blank=True, related_name='_checkout_orderlineitem_included_item_options_+', to='orderonline.MenuItemIngredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderonline.menuitem')),
                ('options', models.ManyToManyField(blank=True, related_name='_checkout_orderlineitem_options_+', to='orderonline.MenuItemIngredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
            ],
        ),
    ]
