# Generated by Django 3.2.23 on 2024-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stripe_pid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
