# Generated by Django 3.2.22 on 2024-03-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
