# Generated by Django 3.2.23 on 2024-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_optional',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
