# Generated by Django 3.2.23 on 2024-02-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0002_auto_20240216_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='orderonline.menuitem')),
                ('upgraded_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_from', to='orderonline.menuitem')),
            ],
        ),
    ]
