# Generated by Django 3.2.23 on 2024-02-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0003_menuitemupgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('included_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in', to='orderonline.menuitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_menu_items', to='orderonline.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItemUpgrade',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='included_items',
            field=models.ManyToManyField(blank=True, related_name='_orderonline_menuitem_included_items_+', through='orderonline.MenuItemIncludedItem', to='orderonline.MenuItem'),
        ),
    ]
