# Generated by Django 3.2.23 on 2024-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0004_auto_20240216_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
