# Generated by Django 3.2.23 on 2024-02-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0006_auto_20240216_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientoption',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderonline.menucategory'),
        ),
    ]
