# Generated by Django 3.2.23 on 2024-02-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0010_alter_ingredientoption_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientoption',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='ingredientoption',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='orderonline.MenuItem'),
        ),
    ]
