# Generated by Django 3.2.23 on 2024-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0013_remove_ingredient_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemingredient',
            name='is_optional',
            field=models.BooleanField(default=True),
        ),
    ]
