# Generated by Django 3.2.23 on 2024-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0014_alter_menuitemingredient_is_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='single_select',
            field=models.BooleanField(default=False),
        ),
    ]
