# Generated by Django 3.2.23 on 2024-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderonline', '0015_ingredient_single_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientoption',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
